export const Question = {
  id: 0,
  question: "Add 483 and 58 together. What is the result?",
  category: 1,
  type: 1,
  level: 1,
  option_A: "431",
  option_B: "441",
  option_C: "531",
  option_D: "541",
  option_E: "551",
  correct_answer: "541",
  hint: "Try setting the question up like this..",
  explanation: null,
  imgsrc: null,
};
